[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1200"
ScreenPadding=""

Font="Open Sans"
FontSize="14"

KeyboardSize="0.4"

RoundCorners="18"

Locale=""
HourFormat="HH:mm"
DateFormat="ddd, MMM dd"

HeaderText=""

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/blanco.jpg"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.35"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="#f2ece1"
DateTextColor="#f2ece1"
TimeTextColor="#f2ece1"

FormBackgroundColor="#141210"
BackgroundColor="#141210"
DimBackgroundColor="#141210"

LoginFieldBackgroundColor="#1c1a17"
PasswordFieldBackgroundColor="#1c1a17"
LoginFieldTextColor="#f2ece1"
PasswordFieldTextColor="#f2ece1"
UserIconColor="#f2ece1"
PasswordIconColor="#f2ece1"

PlaceholderTextColor="#a89f8e"
WarningColor="#c97b63"

LoginButtonTextColor="#141210"
LoginButtonBackgroundColor="#f2ece1"
SystemButtonsIconsColor="#f2ece1"
SessionButtonTextColor="#f2ece1"
VirtualKeyboardButtonTextColor="#f2ece1"

DropdownTextColor="#f2ece1"
DropdownSelectedBackgroundColor="#3a352c"
DropdownBackgroundColor="#1c1a17"

HighlightTextColor="#f2ece1"
HighlightBackgroundColor="#3a352c"
HighlightBorderColor="#3a352c"

HoverUserIconColor="#d9c9a8"
HoverPasswordIconColor="#d9c9a8"
HoverSystemButtonsIconsColor="#d9c9a8"
HoverSessionButtonTextColor="#d9c9a8"
HoverVirtualKeyboardButtonTextColor="#d9c9a8"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.4"

HaveFormBackground="false"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="left"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

UseRealName="true"
ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
